apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
  namespace: bohan
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mysql
    spec:
      containers:                                      
      - name: mysql                                   
        image: hub.c.163.com/library/mysql             
        ports: 
        - containerPort: 3306                          
        env:                                          
        - name: MYSQL_ROOT_PASSWORD 
          value: "123456"
        
        
