apiVersion: v1
kind: Pod
metadata:
  name: gitlab
  namespace: bohan
spec:
  nodeSelector:
    deptype: gitlab
  containers:
  - image: gitlab/gitlab-ce:latest
    name: gitlab
    ports:
    - containerPort: 80
      name: http
    - containerPort: 443
      name: https
    - containerPort: 22
      name: ssh
    volumeMounts:
    - mountPath: /etc/gitlab
      name: gitlab-volume-conf
    - mountPath: /var/log/gitlab
      name: gitlab-volume-log
    - mountPath: /var/opt/gitlab
      name: gitlab-volume-data
  volumes:
  - name: gitlab-volume-conf
    hostPath:
      path: /k8s/disk/bohan/gitlab/config
  - name: gitlab-volume-log
    hostPath:
      path: /k8s/disk/bohan/gitlab/logs      
  - name: gitlab-volume-data
    hostPath:
      path: /k8s/disk/bohan/gitlab/data
    # ports:
    # - containerPort: 80
    #   name: http


#kubectl label nodes  k8s-worker01  deptype=gitlab
#kubectl create -f  github.yaml
#kubectl get pods,service -n bohan
#kubectl describe pods  gitlab -n bohan




