apiVersion: v1
kind: Service
metadata:
 name: gitlab-service
 namespace: bohan
spec:
 type: NodePort
 ports:
 - name: http
   port: 80
   targetPort: 80
   nodePort: 30024
 - name: https
   port: 443
   targetPort: 443
   nodePort: 30025
 - name: ssh
   port: 22
   targetPort: 22
   nodePort: 30026
 selector:
  name: gitlab